### ISSUE TITLE
not authorized

### ISSUE THREAD

**Issue by Renceron** [Defeatomizer/MCreatorVCSPlugin#10]
### Issue description

Writes when trying Sync local changes with remote workspace
![Снимок экрана от 2023-07-29 18-55-35](https://github.com/Defeatomizer/MCreatorVCSPlugin/assets/110835266/c5f15dc2-8772-404d-a082-88ffba61fd14)

### How to reproduce this issue?

1.log in
2. start sync

### Operating system

Linux

### Details

Mcreator 2023.2

plugin 2023.2.1

OS: Fedora

GitHub version: start sync

### Remote repository

https://github.com/largenton/custom-npcs-by-gearmodpack

### Logs

org.eclipse.jgit.api.errors.TransportException: https://github.com/largenton/custom-npcs-by-gearmodpack: not authorized
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:159) ~[?:?]
	at net.mcreator.vcs.ui.actions.impl.SyncLocalWithRemoteAction.lambda$new$1(SyncLocalWithRemoteAction.java:191) ~[?:?]
	at net.mcreator.ui.action.UnregisteredAction.actionPerformed(UnregisteredAction.java:73) ~[mcreator.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297) ~[?:?]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:746) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:744) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:743) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/largenton/custom-npcs-by-gearmodpack: not authorized
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:685) ~[?:?]
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:627) ~[?:?]
	at org.eclipse.jgit.transport.TransportHttp.openPush(TransportHttp.java:541) ~[?:?]
	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:139) ~[?:?]
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1473) ~[?:?]
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:149) ~[?:?]
	... 39 more

**Comment by Defeatomizer** [comment]
Did you use an access token? GitHub accounts verification doesn't work with their passwords at the moment.

**Comment by Renceron** [comment]
I haven't tried, it but I will try

**Comment by Defeatomizer** [comment]
@Renceron, do you still have this problem?

**Comment by Defeatomizer** [comment]
The linked repository seems to not exist/be visible, neither at provided URL nor on your account.
